### ISSUE TITLE
precipitationRain always null

### ISSUE THREAD

**Issue by Araskson** [ioBroker/ioBroker.openweathermap#27]
There is an error in the code by iobroker installed adapter.
main.js: Line 161:
counts.precipitationRain = counts.precipitationSnow || 0;
instead of
counts.precipitationSnow = counts.precipitationSnow || 0;

this error is not in the github version.

Regards
Araskson

**Comment by mat130780** [comment]
Yes, I can confirm that error. I would like to use this adapter to control an automatic irrigation system. 
Could this please be corrected so that we will get the precipitation values? Thanks a lot in advance.

**Comment by tugsi** [comment]
Precipitation isn't any more in the JSON-String:
`{
  "coord": {
    "lon": 6.73,
    "lat": 51.57
  },
  "weather": [
    {
      "id": 804,
      "main": "Clouds",
      "description": "Bedeckt",
      "icon": "04n"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 3.71,
    "feels_like": -0.89,
    "temp_min": 3.33,
    "temp_max": 3.89,
    "pressure": 1003,
    "humidity": 92
  },
  "visibility": 10000,
  "wind": {
    "speed": 4.31,
    "deg": 235
  },
  "clouds": {
    "all": 100
  },
  "dt": 1609352339,
  "sys": {
    "type": 3,
    "id": 2012966,
    "country": "DE",
    "sunrise": 1609313947,
    "sunset": 1609342325
  },
  "timezone": 3600,
  "id": 2936871,
  "name": "Dinslaken",
  "cod": 200
}`

It has to be changed into XML-String, in order to get the precipitation mode, but only this:
`<current>
<city id="2936871" name="Dinslaken">
<coord lon="6.73" lat="51.57"/>
<country>DE</country>
<timezone>3600</timezone>
<sun rise="2020-12-30T07:39:07" set="2020-12-30T15:32:05"/>
</city>
<temperature value="3.71" min="3.33" max="3.89" unit="celsius"/>
<feels_like value="-0.89" unit="celsius"/>
<humidity value="92" unit="%"/>
<pressure value="1003" unit="hPa"/>
<wind>
<speed value="4.31" unit="m/s" name="Gentle Breeze"/>
<gusts/>
<direction value="235" code="SW" name="Southwest"/>
</wind>
<clouds value="100" name="Bedeckt"/>
<visibility value="10000"/>
<precipitation mode="no"/>
<weather number="804" value="Bedeckt" icon="04n"/>
<lastupdate value="2020-12-30T18:15:00"/>
</current>`

**Comment by Apollon77** [comment]
duplicate #1 ?
